# Generated by Django 6.0.4 on 2026-04-17 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_sped', models.DateField(blank=True, null=True, verbose_name='Data de Início do SPED')),
                ('data_fim_sped', models.DateField(blank=True, null=True, verbose_name='Data de Fim do SPED')),
                ('cod_part', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Participante')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('codigo_pais', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do País')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ/CPF')),
                ('ie', models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual')),
                ('codigo_municipio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do Município')),
                ('suframa', models.CharField(blank=True, max_length=20, null=True, verbose_name='SUFRAMA')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número')),
                ('complemento', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Notas_participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('data_inicio_sped', models.DateField(blank=True, null=True, verbose_name='Data de Início do SPED')),
                ('data_fim_sped', models.DateField(blank=True, null=True, verbose_name='Data de Fim do SPED')),
                ('numero_nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota')),
                ('codigo_uf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da UF')),
                ('chave_nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave da Nota')),
                ('status', models.CharField(blank=True, max_length=15, null=True, verbose_name='Status')),
                ('tipo_operacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Operação')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('mes_sped', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês do SPED')),
                ('data_entrada_saida', models.DateField(blank=True, null=True, verbose_name='Data de Entrada e Saída')),
                ('tipo_documento', models.CharField(blank=True, max_length=4, null=True, verbose_name='Tipo de Documento')),
                ('serie_documento', models.CharField(blank=True, max_length=4, null=True, verbose_name='Série do Documento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa', verbose_name='Empresa')),
                ('part_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacao.participantes', verbose_name='Participante Titular')),
            ],
            options={
                'verbose_name': 'Nota do Participante',
                'verbose_name_plural': 'Notas dos Participantes',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_itens_sped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_sped', models.DateField(blank=True, null=True, verbose_name='Data de Início do SPED')),
                ('data_fim_sped', models.DateField(blank=True, null=True, verbose_name='Data de Fim do SPED')),
                ('codigo_prod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Produto')),
                ('descricao_prod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição do Produto')),
                ('unidade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade')),
                ('tipo_item', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Item')),
                ('ncm', models.CharField(blank=True, max_length=50, null=True, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEST')),
                ('saldo_inicial_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Inicial do Produto')),
                ('genero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gênero')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacao.produtobase', verbose_name='Produto ID')),
            ],
            options={
                'verbose_name': 'Cadastro de Item SPED',
                'verbose_name_plural': 'Cadastros de Itens SPED',
            },
        ),
        migrations.CreateModel(
            name='Produtos_notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo da Nota')),
                ('data_inicio_sped', models.DateField(blank=True, null=True, verbose_name='Data de Início do SPED')),
                ('data_fim_sped', models.DateField(blank=True, null=True, verbose_name='Data de Fim do SPED')),
                ('codigo_prod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Produto')),
                ('descricao_prod', models.TextField(blank=True, null=True, verbose_name='Descrição do Produto')),
                ('unidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade')),
                ('quantidade_prod', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Quantidade do Produto')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Total')),
                ('cfop_prod', models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP do Produto')),
                ('ncm', models.CharField(blank=True, max_length=50, null=True, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEST')),
                ('cst', models.CharField(blank=True, max_length=15, null=True, verbose_name='CST')),
                ('aliquota_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Alíquota do ICMS')),
                ('base_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Base do ICMS')),
                ('valor_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor do IPI')),
                ('valor_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor do PIS')),
                ('valor_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor do ICMS')),
                ('tipo_movimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Movimento')),
                ('cod_lancamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Lançamento')),
                ('tipo_item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Item')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa', verbose_name='Empresa')),
                ('nota_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacao.notas_participantes', verbose_name='Nota Titular')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacao.produtobase', verbose_name='Produto ID')),
            ],
            options={
                'verbose_name': 'Produto da Nota',
                'verbose_name_plural': 'Produtos das Notas',
            },
        ),
        migrations.CreateModel(
            name='ValidacaoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('progresso', models.PositiveIntegerField(default=0, verbose_name='Progresso')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_sped', models.DateField(blank=True, null=True, verbose_name='Data do SPED')),
                ('sped', models.BooleanField(default=False, verbose_name='SPED')),
                ('xml', models.BooleanField(default=False, verbose_name='XML')),
                ('due', models.BooleanField(default=False, verbose_name='DUE')),
                ('mes_sped', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês do SPED')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validacoes', to='cadastro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Status da Validação',
                'verbose_name_plural': 'Status das Validações',
            },
        ),
        migrations.CreateModel(
            name='ValidacaoDataConcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sped', models.DateField(verbose_name='Data do SPED')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado Em')),
                ('mes_sped', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês do SPED')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_concluidas', to='cadastro.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Data de Validação Concluída',
                'verbose_name_plural': 'Datas de Validação Concluídas',
                'unique_together': {('empresa', 'data_sped')},
            },
        ),
    ]
