# Generated by Django 6.0.4 on 2026-04-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos_notas',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='cadastro_itens_sped',
            name='produto',
        ),
        migrations.AddField(
            model_name='cadastro_itens_sped',
            name='produto_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacao.produtos_notas', verbose_name='Produto titular'),
        ),
        migrations.DeleteModel(
            name='ProdutoBase',
        ),
    ]
