# Generated by Django 6.0.4 on 2026-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacao', '0002_remove_produtos_notas_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_itens_sped',
            name='saldo_final_produto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Inicial do Produto'),
        ),
    ]
