# Generated by Django 6.0.4 on 2026-05-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0003_cadastro_itens_sped_saldo_final_produto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cadastro_itens_sped",
        ),
    ]
