# Generated by Django 6.0.4 on 2026-07-15 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacao', '0004_delete_cadastro_itens_sped'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTransporteD100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(blank=True, default='D100', max_length=4, null=True, verbose_name='Código do Registro')),
                ('ind_oper', models.CharField(blank=True, max_length=1, null=True, verbose_name='Indicador do Tipo de Operação')),
                ('ind_emit', models.CharField(blank=True, max_length=1, null=True, verbose_name='Indicador do Emitente')),
                ('cod_mod', models.CharField(blank=True, max_length=2, null=True, verbose_name='Modelo do Documento')),
                ('cod_sit', models.CharField(blank=True, max_length=2, null=True, verbose_name='Código da Situação')),
                ('ser', models.CharField(blank=True, max_length=4, null=True, verbose_name='Série')),
                ('sub', models.CharField(blank=True, max_length=3, null=True, verbose_name='Subsérie')),
                ('num_doc', models.IntegerField(blank=True, null=True, verbose_name='Número do Documento')),
                ('chv_cte', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave do CT-e')),
                ('dt_doc', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('dt_a_p', models.DateField(blank=True, null=True, verbose_name='Data de Entrada/Prestação')),
                ('tp_cte', models.IntegerField(verbose_name='Tipo do CT-e')),
                ('chv_cte_ref', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave do CT-e de Referência')),
                ('vl_doc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total do Documento')),
                ('vl_desc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total do Desconto')),
                ('ind_frt', models.CharField(blank=True, max_length=1, null=True, verbose_name='Indicador do Frete')),
                ('vl_serv', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Serviço')),
                ('vl_bc_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Base de Cálculo do ICMS')),
                ('vl_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor do ICMS')),
                ('vl_nt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Não Tributado')),
                ('cod_inf', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código da Informação Complementar')),
                ('cod_cta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conta Contábil')),
                ('cod_mun_orig', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código IBGE do Município de Origem')),
                ('cod_mun_dest', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código IBGE do Município de Destino')),
                ('cod_part', models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='validacao.participantes', verbose_name='Código do Participante')),
            ],
            options={
                'verbose_name': 'Registro D100',
                'verbose_name_plural': 'Registros D100',
            },
        ),
        migrations.CreateModel(
            name='RegistroTransporteD190',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(default='D190', max_length=4, verbose_name='Código do Registro')),
                ('cst_icms', models.CharField(max_length=3, verbose_name='Código da Situação Tributária (CST)')),
                ('cfop', models.CharField(max_length=4, verbose_name='Código Fiscal de Operações (CFOP)')),
                ('aliq_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alíquota do ICMS')),
                ('vl_opr', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Operação')),
                ('vl_bc_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Base de Cálculo do ICMS')),
                ('vl_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor do ICMS')),
                ('vl_red_bc', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor da Redução da BC / ICMS-ST')),
                ('cod_obs', models.CharField(blank=True, max_length=6, null=True, verbose_name='Código da Observação')),
                ('registro_d100', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analiticos', to='validacao.registrotransported100', verbose_name='Documento de Transporte (D100)')),
            ],
            options={
                'verbose_name': 'Registro D190',
                'verbose_name_plural': 'Registros D190',
            },
        ),
    ]
