# Generated by Django 6.0.4 on 2026-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0005_registrotransported100_registrotransported190"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantes",
            name="cod_part",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código do Participante",
            ),
        ),
    ]
