# Generated by Django 6.0.4 on 2026-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0006_alter_participantes_cod_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="validacaodataconcluida",
            name="tipo_validacao",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Tipo documento"
            ),
        ),
        migrations.AddField(
            model_name="validacaostatus",
            name="tipo_validacao",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Tipo documento"
            ),
        ),
    ]
