# Generated by Django 6.0.4 on 2026-07-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0007_validacaodataconcluida_tipo_validacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrotransported100",
            name="data_final_sped",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data final sped"
            ),
        ),
        migrations.AddField(
            model_name="registrotransported100",
            name="data_inicio_sped",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data inicio sped"
            ),
        ),
        migrations.AddField(
            model_name="registrotransported100",
            name="mes_referencia",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Mês referencia"
            ),
        ),
        migrations.AddField(
            model_name="registrotransported190",
            name="data_final_sped",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data final sped"
            ),
        ),
        migrations.AddField(
            model_name="registrotransported190",
            name="data_inicio_sped",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data inicio sped"
            ),
        ),
        migrations.AddField(
            model_name="registrotransported190",
            name="mes_referencia",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Mês referencia"
            ),
        ),
    ]
