# Generated by Django 6.0.4 on 2026-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0008_registrotransported100_data_final_sped_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrotransported100",
            name="cod_inf",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Código da Informação Complementar",
            ),
        ),
    ]
