# Generated by Django 6.0.4 on 2026-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0009_alter_registrotransported100_cod_inf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrotransported100",
            name="cod_mun_dest",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Código IBGE do Município de Destino",
            ),
        ),
        migrations.AlterField(
            model_name="registrotransported100",
            name="cod_mun_orig",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Código IBGE do Município de Origem",
            ),
        ),
    ]
