# Generated by Django 6.0.4 on 2026-07-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0032_empresa_status"),
        ("validacao", "0010_alter_registrotransported100_cod_mun_dest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrotransported100",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.empresa",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="registrotransported190",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.empresa",
                verbose_name="Empresa",
            ),
        ),
    ]
