# Generated by Django 6.0.4 on 2026-07-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0032_empresa_status"),
        ("validacao", "0011_registrotransported100_empresa_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participantes",
            options={},
        ),
        migrations.AddConstraint(
            model_name="participantes",
            constraint=models.UniqueConstraint(
                fields=("cod_part", "empresa", "data_inicio_sped"),
                name="unique_participante_por_empresa_periodo",
            ),
        ),
    ]
