# Generated by Django 6.0.4 on 2026-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0012_alter_participantes_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantes",
            name="cod_part",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Código do Participante",
            ),
        ),
    ]
