# Generated by Django 6.0.6 on 2026-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacao', '0014_registrocomunicacaod500_registrocomunicacaod590_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocomunicacaod590',
            name='cod_obs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código da Observação'),
        ),
        migrations.AlterField(
            model_name='registroenergiac590',
            name='cod_obs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código da Observação'),
        ),
        migrations.AlterField(
            model_name='registrotransported190',
            name='cod_obs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código da Observação'),
        ),
    ]
