# Generated by Django 6.0.4 on 2026-07-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0015_alter_registrocomunicacaod590_cod_obs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrocomunicacaod500",
            name="sub",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="Subsérie"
            ),
        ),
        migrations.AlterField(
            model_name="registrocomunicacaod590",
            name="cst_icms",
            field=models.CharField(
                max_length=7, verbose_name="Código da Situação Tributária (CST)"
            ),
        ),
        migrations.AlterField(
            model_name="registroenergiac500",
            name="sub",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="Subsérie"
            ),
        ),
        migrations.AlterField(
            model_name="registroenergiac590",
            name="cst_icms",
            field=models.CharField(
                max_length=7, verbose_name="Código da Situação Tributária (CST)"
            ),
        ),
        migrations.AlterField(
            model_name="registrotransported100",
            name="sub",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="Subsérie"
            ),
        ),
        migrations.AlterField(
            model_name="registrotransported190",
            name="cst_icms",
            field=models.CharField(
                max_length=7, verbose_name="Código da Situação Tributária (CST)"
            ),
        ),
    ]
