# Generated by Django 6.0.4 on 2026-07-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0016_alter_registrocomunicacaod500_sub_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validacaostatus",
            name="tipo_validacao",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Tipo documento"
            ),
        ),
    ]
