# Generated by Django 6.0.4 on 2026-07-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0017_alter_validacaostatus_tipo_validacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validacaodataconcluida",
            name="tipo_validacao",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Tipo documento"
            ),
        ),
    ]
