# Generated by Django 6.0.4 on 2026-08-07 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0018_alter_validacaodataconcluida_tipo_validacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tabela",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Tabela"
                    ),
                ),
                ("campo", models.CharField(max_length=100, verbose_name="Campo")),
                (
                    "valor_antigo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor antigo"
                    ),
                ),
                (
                    "valor_novo",
                    models.TextField(blank=True, null=True, verbose_name="Valor novo"),
                ),
                (
                    "mes_sped",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Mês do sped"
                    ),
                ),
                ("data_alteracao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario responsável",
                    ),
                ),
            ],
        ),
    ]
