# Generated by Django 6.0.4 on 2026-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validacao", "0019_movimentacaohistorico"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaohistorico",
            name="ano_sped",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Ano do sped"
            ),
        ),
    ]
