# Generated by Django 6.0.4 on 2026-08-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permissions",
            name="historico",
        ),
    ]
