# Generated by Django 6.0.4 on 2026-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ladca', models.CharField(blank=True, max_length=4, null=True, verbose_name='Empresa')),
                ('cod_ver', models.CharField(blank=True, max_length=18, null=True, verbose_name='Código de Verificação')),
                ('cod_fin', models.CharField(blank=True, max_length=18, null=True, verbose_name='Código Financeiro')),
                ('razao_social', models.CharField(blank=True, max_length=70, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('opc_cred_outorgado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Opcão de Crédito Outorgado')),
                ('inscricao_estadual_intima', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual Intima')),
                ('indicador_atividade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Indicador de Atividade')),
                ('configuracao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Configuração')),
                ('codigo_municipio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Município')),
                ('nome_fantasia', models.CharField(blank=True, max_length=70, null=True, verbose_name='Nome Fantasia')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('numero_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número do Endereço')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('metodo_rateio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Rateio')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cnae', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNAE')),
                ('indicador_movimento', models.CharField(blank=True, max_length=2, null=True, verbose_name='Indicador de Movimento')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=70, null=True, verbose_name='Empresa')),
                ('codigo_prod', models.CharField(blank=True, max_length=70, null=True, verbose_name='Código do Produto')),
                ('descricao_prod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição do Produto')),
                ('unidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade')),
                ('tipo_produto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do Produto')),
                ('genero', models.CharField(blank=True, max_length=70, null=True, verbose_name='Genêro')),
                ('ncm', models.CharField(blank=True, max_length=7, null=True, verbose_name='NCM')),
                ('descricao_complementar', models.CharField(blank=True, max_length=70, null=True, verbose_name='Descrição Complementar')),
                ('codigo_cest', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Cest')),
                ('saldo_inicial_prod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Inicial Produto')),
                ('saldo_inicial_icms', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Inicial Icms')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
