# Generated by Django 6.0.4 on 2026-04-27 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Regra')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('empresa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa', verbose_name='Empresa ID')),
                ('regra_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.regras', verbose_name='Regra ID')),
            ],
        ),
    ]
