# Generated by Django 6.0.4 on 2026-04-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_regras_empresaregra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresaregra',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresaregra',
            name='regra_id',
        ),
        migrations.AddField(
            model_name='empresaregra',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.regras', verbose_name='Regra ID'),
        ),
        migrations.AlterField(
            model_name='regras',
            name='nome_regra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome das Regras'),
        ),
    ]
