# Generated by Django 6.0.4 on 2026-04-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_regras_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='regras',
            name='valor',
            field=models.CharField(blank=True, choices=[('PRD', 'PRD'), ('A', 'A'), ('ABC', 'ABC'), ('1', '1'), ('8', '8'), ('01', '01'), ('A1', 'A1'), ('XYZ', 'XYZ'), ('99', '99'), ('B2', 'B2'), ('numerico', 'Numérico'), ('alfanumerico', 'Alfanumérico'), ('6', '6'), ('7', '7'), ('8', '8'), ('10', '10'), ('11', '11'), ('-', 'Hífen (-)'), ('/', 'Barra (/)'), ('.', 'Ponto (.)'), ('espaco', 'Espaço')], max_length=50, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='regras',
            name='categoria',
            field=models.CharField(blank=True, choices=[('importacao', 'Importação'), ('calculo', 'Cálculo')], max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='regras',
            name='nome_regra',
            field=models.CharField(blank=True, choices=[('prefixo', 'Prefixo'), ('sufixo', 'Sufixo'), ('caractere', 'Caractere'), ('tamanho', 'Tamanho'), ('formato', 'Formato')], max_length=100, null=True, verbose_name='Nome das Regras'),
        ),
    ]
