# Generated by Django 6.0.4 on 2026-04-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_regras_valor_alter_regras_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento'),
        ),
    ]
