# Generated by Django 6.0.4 on 2026-05-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_empresa_complemento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
