# Generated by Django 6.0.4 on 2026-05-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_delete_produtos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_regra",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prefixo", "Prefixo"),
                            ("sufixo", "Sufixo"),
                            ("caractere", "Caractere"),
                            ("tamanho", "Tamanho"),
                            ("formato", "Formato"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Nome Regra:",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[("importacao", "Importação"), ("calculo", "Cálculo")],
                        max_length=100,
                        null=True,
                        verbose_name="Categoria:",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRD", "PRD"),
                            ("A", "A"),
                            ("ABC", "ABC"),
                            ("1", "1"),
                            ("8", "8"),
                            ("01", "01"),
                            ("A1", "A1"),
                            ("XYZ", "XYZ"),
                            ("99", "99"),
                            ("B2", "B2"),
                            ("numerico", "Numérico"),
                            ("alfanumerico", "Alfanumérico"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("10", "10"),
                            ("11", "11"),
                            ("-", "Hífen (-)"),
                            ("/", "Barra (/)"),
                            (".", "Ponto (.)"),
                            ("espaco", "Espaço"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Valor:",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="empresaregra",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.empresa",
                verbose_name="Empresa:",
            ),
        ),
        migrations.AlterField(
            model_name="empresaregra",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Status:"),
        ),
        migrations.AlterField(
            model_name="empresaregra",
            name="regra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.regra",
                verbose_name="Regra:",
            ),
        ),
        migrations.DeleteModel(
            name="Regras",
        ),
    ]
