# Generated by Django 6.0.4 on 2026-05-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0008_regra_alter_empresaregra_empresa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regra",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="regra",
            name="valor",
        ),
        migrations.AddField(
            model_name="regra",
            name="regra",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRD", "PRD"),
                    ("A", "A"),
                    ("ABC", "ABC"),
                    ("1", "1"),
                    ("8", "8"),
                    ("01", "01"),
                    ("A1", "A1"),
                    ("XYZ", "XYZ"),
                    ("99", "99"),
                    ("B2", "B2"),
                    ("numerico", "Numérico"),
                    ("alfanumerico", "Alfanumérico"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("10", "10"),
                    ("11", "11"),
                    ("-", "Hífen (-)"),
                    ("/", "Barra (/)"),
                    (".", "Ponto (.)"),
                    ("espaco", "Espaço"),
                ],
                max_length=50,
                null=True,
                verbose_name="Regras:",
            ),
        ),
        migrations.AlterField(
            model_name="regra",
            name="nome_regra",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Apelido pra regra:"
            ),
        ),
    ]
