# Generated by Django 6.0.4 on 2026-05-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0009_remove_regra_categoria_remove_regra_valor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regra",
            name="nome_regra",
        ),
        migrations.AddField(
            model_name="regra",
            name="tipo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="De qual tipo é:"
            ),
        ),
        migrations.AlterField(
            model_name="regra",
            name="regra",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Prefixo", [("PRD", "PRD"), ("A", "A"), ("ABC", "ABC")]),
                    (
                        "Tamanho",
                        [
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("10", "10"),
                            ("11", "11"),
                        ],
                    ),
                    (
                        "Formato",
                        [("numerico", "Numérico"), ("alfanumerico", "Alfanumérico")],
                    ),
                    (
                        "Caractere",
                        [
                            ("-", "Hífen (-)"),
                            ("/", "Barra (/)"),
                            (".", "Ponto (.)"),
                            ("espaco", "Espaço"),
                        ],
                    ),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo regra:",
            ),
        ),
    ]
