# Generated by Django 6.0.4 on 2026-05-19 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0010_remove_regra_nome_regra_regra_tipo_alter_regra_regra"),
        ("validacao", "0004_delete_cadastro_itens_sped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regra",
            name="regra",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Prefixo", [("PRD", "PRD"), ("A", "A"), ("ABC", "ABC")]),
                    (
                        "Tamanho",
                        [
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("10", "10"),
                            ("11", "11"),
                        ],
                    ),
                    (
                        "Formato",
                        [("numerico", "Numérico"), ("alfanumerico", "Alfanumérico")],
                    ),
                    ("Caractere", [("-", "Hífen (-)")]),
                    ("Sufixo", [("01", "01"), ("1", "1"), ("A", "A"), ("B", "B")]),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo regra:",
            ),
        ),
        migrations.AlterField(
            model_name="regra",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prefixo", "Prefixo"),
                    ("tamanho", "tamanho"),
                    ("formato", "Formato"),
                    ("caractere", "Caractere"),
                    ("sufixo", "Sufixo"),
                ],
                max_length=100,
                null=True,
                verbose_name="De qual tipo é:",
            ),
        ),
        migrations.CreateModel(
            name="Cadastro_itens_sped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio_sped",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início do SPED"
                    ),
                ),
                (
                    "data_fim_sped",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Fim do SPED"
                    ),
                ),
                (
                    "codigo_prod",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código do Produto",
                    ),
                ),
                (
                    "descricao_prod",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Descrição do Produto",
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Unidade"
                    ),
                ),
                (
                    "tipo_item",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Tipo de Item",
                    ),
                ),
                (
                    "ncm",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="NCM"
                    ),
                ),
                (
                    "cest",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="CEST"
                    ),
                ),
                (
                    "saldo_inicial_produto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Saldo Inicial do Produto",
                    ),
                ),
                (
                    "saldo_final_produto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Saldo Inicial do Produto",
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gênero"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.empresa",
                    ),
                ),
                (
                    "produto_titular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validacao.produtos_notas",
                        verbose_name="Produto titular",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadastro de Item SPED",
                "verbose_name_plural": "Cadastros de Itens SPED",
            },
        ),
    ]
