# Generated by Django 6.0.4 on 2026-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0011_alter_regra_regra_alter_regra_tipo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Itens_sem_cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Codigo_sem_cadastro",
                    ),
                ),
                (
                    "tipo_processamento",
                    models.CharField(
                        blank=True, null=True, verbose_name="Tipo processamento"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("codigo", "tipo_processamento")},
            },
        ),
    ]
