# Generated by Django 6.0.4 on 2026-05-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0012_itens_sem_cadastro"),
    ]

    operations = [
        migrations.CreateModel(
            name="nova_regra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nova regra"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Tipo regra"
                    ),
                ),
            ],
        ),
    ]
