# Generated by Django 6.0.4 on 2026-05-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0013_nova_regra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nova_regra",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prefixo", "Prefixo"),
                    ("sufixo", "Sufixo"),
                    ("tamanho", "Tamanho"),
                    ("caractere", "Caractere"),
                    ("formato", "Formato"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo regra",
            ),
        ),
        migrations.AlterField(
            model_name="regra",
            name="regra",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ("Prefixo", [("PRD", "PRD"), ("A", "A"), ("ABC", "ABC")]),
                    (
                        "Tamanho",
                        [
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("10", "10"),
                            ("11", "11"),
                        ],
                    ),
                    (
                        "Formato",
                        [("numerico", "Numérico"), ("alfanumerico", "Alfanumérico")],
                    ),
                    ("Caractere", [("-", "Hífen (-)")]),
                    ("Sufixo", [("01", "01"), ("1", "1"), ("A", "A"), ("B", "B")]),
                ],
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.nova_regra",
                verbose_name="Regra:",
            ),
        ),
    ]
