# Generated by Django 6.0.4 on 2026-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0014_alter_nova_regra_tipo_alter_regra_regra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regra",
            name="regra",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Prefixo", [("PRD", "PRD"), ("A", "A"), ("ABC", "ABC")]),
                    (
                        "Tamanho",
                        [
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("10", "10"),
                            ("11", "11"),
                        ],
                    ),
                    (
                        "Formato",
                        [("numerico", "Numérico"), ("alfanumerico", "Alfanumérico")],
                    ),
                    ("Caractere", [("-", "Hífen (-)")]),
                    ("Sufixo", [("01", "01"), ("1", "1"), ("A", "A"), ("B", "B")]),
                ],
                null=True,
                verbose_name="Regra:",
            ),
        ),
    ]
