# Generated by Django 6.0.4 on 2026-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0016_alter_regra_regra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regra",
            name="regra",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Regra:"
            ),
        ),
        migrations.DeleteModel(
            name="nova_regra",
        ),
    ]
