# Generated by Django 6.0.4 on 2026-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0017_alter_regra_regra_delete_nova_regra"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="itens_sem_cadastro",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="itens_sem_cadastro",
            name="codigo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código sem cadastro"
            ),
        ),
    ]
