# Generated by Django 6.0.4 on 2026-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0018_alter_itens_sem_cadastro_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itens_sem_cadastro",
            name="nota_refe",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Nota referência"
            ),
        ),
    ]
