# Generated by Django 6.0.4 on 2026-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0019_itens_sem_cadastro_nota_refe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itens_sem_cadastro",
            name="nota_refe",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nota referência"
            ),
        ),
    ]
