# Generated by Django 6.0.4 on 2026-05-25 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0020_alter_itens_sem_cadastro_nota_refe"),
    ]

    operations = [
        migrations.AddField(
            model_name="itens_sem_cadastro",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.empresa",
            ),
        ),
        migrations.CreateModel(
            name="ValidacaoItensSemCadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em andamento"),
                            ("concluido", "Concluído"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro.empresa",
                    ),
                ),
            ],
        ),
    ]
