# Generated by Django 6.0.4 on 2026-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0021_itens_sem_cadastro_empresa_validacaoitenssemcadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validacaoitenssemcadastro",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pendente", "Pendente"),
                    ("em_andamento", "Em andamento"),
                    ("concluido", "Concluído"),
                ],
                default=False,
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
