# Generated by Django 6.0.4 on 2026-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0022_alter_validacaoitenssemcadastro_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validacaoitenssemcadastro",
            name="status",
            field=models.CharField(
                blank=True,
                default=False,
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
