# Generated by Django 6.0.4 on 2026-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0023_alter_validacaoitenssemcadastro_status"),
        ("validacao", "0004_delete_cadastro_itens_sped"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cadastro_itens_sped",
            options={},
        ),
        migrations.AddField(
            model_name="cadastro_itens_sped",
            name="mes_ref",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mês ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="cadastro_itens_sped",
            constraint=models.UniqueConstraint(
                fields=("codigo_prod", "empresa", "mes_ref"),
                name="unique_codigo_mes_empresa",
            ),
        ),
    ]
