# Generated by Django 6.0.4 on 2026-06-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0024_alter_cadastro_itens_sped_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validacaoitenssemcadastro",
            name="qtd_pendencia",
            field=models.IntegerField(
                default=0, verbose_name="Quantidade de pendência"
            ),
        ),
    ]
