# Generated by Django 6.0.4 on 2026-06-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0025_validacaoitenssemcadastro_qtd_pendencia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cadastro_itens_sped",
            options={
                "verbose_name": "Cadastro de Item SPED",
                "verbose_name_plural": "Cadastros de Itens SPED",
            },
        ),
    ]
