# Generated by Django 6.0.4 on 2026-06-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0026_alter_cadastro_itens_sped_options"),
        ("validacao", "0004_delete_cadastro_itens_sped"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cadastro_itens_sped",
            name="unique_codigo_mes_empresa",
        ),
        migrations.AddConstraint(
            model_name="cadastro_itens_sped",
            constraint=models.UniqueConstraint(
                fields=("codigo_prod", "empresa"), name="unique_codigo_mes_empresa"
            ),
        ),
    ]
