# Generated by Django 6.0.4 on 2026-06-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastro",
            "0027_remove_cadastro_itens_sped_unique_codigo_mes_empresa_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validacaoitenssemcadastro",
            name="empresa",
        ),
        migrations.DeleteModel(
            name="Itens_sem_cadastro",
        ),
        migrations.DeleteModel(
            name="ValidacaoItensSemCadastro",
        ),
    ]
