# Generated by Django 6.0.4 on 2026-06-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0028_remove_validacaoitenssemcadastro_empresa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro_itens_sped",
            name="cest",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="CEST"
            ),
        ),
        migrations.AlterField(
            model_name="cadastro_itens_sped",
            name="codigo_prod",
            field=models.CharField(
                blank=True, max_length=70, null=True, verbose_name="Código do Produto"
            ),
        ),
        migrations.AlterField(
            model_name="cadastro_itens_sped",
            name="descricao_prod",
            field=models.CharField(
                blank=True,
                max_length=70,
                null=True,
                verbose_name="Descrição do Produto",
            ),
        ),
    ]
