# Generated by Django 6.0.4 on 2026-06-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0030_alter_cadastro_itens_sped_cest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro_itens_sped",
            name="cest",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CEST"
            ),
        ),
        migrations.AlterField(
            model_name="cadastro_itens_sped",
            name="codigo_prod",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Código do Produto"
            ),
        ),
        migrations.AlterField(
            model_name="cadastro_itens_sped",
            name="descricao_prod",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Descrição do Produto",
            ),
        ),
        migrations.AlterField(
            model_name="cadastro_itens_sped",
            name="genero",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Gênero"
            ),
        ),
    ]
