# Generated by Django 6.0.4 on 2026-07-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0031_alter_cadastro_itens_sped_cest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Status"),
        ),
    ]
