# Generated by Django 6.0.4 on 2026-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0032_empresa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastro_itens_sped",
            name="ano_sped",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Ano sped"
            ),
        ),
    ]
