# Generated by Django 6.0.4 on 2026-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0033_cadastro_itens_sped_ano_sped"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="indicador_perfil",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Indicador de perfil"
            ),
        ),
    ]
