# Generated by Django 6.0.4 on 2026-08-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0034_empresa_indicador_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="indicador_atividade",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Indicador de Atividade",
            ),
        ),
    ]
