# Generated by Django 6.0.4 on 2026-08-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tela_modificada",
                    models.CharField(
                        choices=[
                            ("movimentacao", "Movimentação"),
                            ("metodo_rateio", "Método Rateio"),
                            ("cadastro", "Cadastro"),
                            ("gerar_arquivo", "Geração de Arquivo"),
                        ],
                        max_length=30,
                        verbose_name="Tela modificada",
                    ),
                ),
                (
                    "tabela",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Tabela"
                    ),
                ),
                ("campo", models.CharField(max_length=100, verbose_name="Campo")),
                (
                    "valor_antigo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor antigo"
                    ),
                ),
                (
                    "valor_novo",
                    models.TextField(blank=True, null=True, verbose_name="Valor novo"),
                ),
                (
                    "mes_sped",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="Mês do sped"
                    ),
                ),
                (
                    "ano_sped",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Ano do sped"
                    ),
                ),
                ("data_alteracao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico",
                "verbose_name_plural": "Históricos",
                "ordering": ["-data_alteracao"],
            },
        ),
    ]
