# Generated by Django 6.0.4 on 2026-08-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="entidade_pai",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Entidade Pai"
            ),
        ),
        migrations.AddField(
            model_name="historico",
            name="entidade_titular",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Entidade titular"
            ),
        ),
        migrations.AlterField(
            model_name="historico",
            name="tela_modificada",
            field=models.CharField(
                choices=[
                    ("movimentacao", "Movimentação"),
                    ("metodo_rateio", "Método Rateio"),
                    ("cadastro", "Cadastro"),
                    ("gerar_arquivo", "Arquivo baixados"),
                ],
                max_length=30,
                verbose_name="Tela modificada",
            ),
        ),
    ]
