# Generated by Django 6.0.4 on 2026-08-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "historico",
            "0002_historico_entidade_pai_historico_entidade_titular_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="prod_titular",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Produto titular"
            ),
        ),
    ]
