# Generated by Django 6.0.4 on 2026-08-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0035_alter_empresa_indicador_atividade"),
        ("historico", "0003_historico_prod_titular"),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.empresa",
                verbose_name="Empresa ID",
            ),
        ),
    ]
