# Generated by Django 6.0.4 on 2026-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historico", "0004_historico_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="historico",
            name="nome_empresa",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nome empresa"
            ),
        ),
    ]
