# Generated by Django 6.0.4 on 2026-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historico", "0005_historico_nome_empresa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historico",
            name="entidade_titular",
        ),
        migrations.RemoveField(
            model_name="historico",
            name="prod_titular",
        ),
        migrations.AddField(
            model_name="historico",
            name="entidade_filho",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Entidade Filho"
            ),
        ),
        migrations.AddField(
            model_name="historico",
            name="part_titular",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Participante Titular",
            ),
        ),
        migrations.AlterField(
            model_name="historico",
            name="entidade_pai",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Entidade pai"
            ),
        ),
    ]
