# Generated by Django 6.0.4 on 2026-04-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('data_referencia', models.DateField(blank=True, null=True, verbose_name='Data de Referência')),
                ('categoria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Categoria')),
                ('centro_custo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Centro de Custo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('documento_fiscal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Documento Fiscal')),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fornecedor')),
                ('conta_contabil', models.CharField(blank=True, max_length=255, null=True, verbose_name='Conta Contábil')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('percentual_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Percentual Aplicado')),
                ('valor_alocado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Alocado')),
                ('icms_passivel_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Icms Passivel de Crédito')),
            ],
            options={
                'verbose_name': 'Planilha de Custo',
                'verbose_name_plural': 'Planilhas de Custo',
            },
        ),
        migrations.CreateModel(
            name='analise_concluida_k23x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_finalizada', models.DateField(blank=True, null=True, verbose_name='Data Finalizada')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('mes_sped', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês do SPED')),
                ('ano_sped', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do SPED')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
            ],
            options={
                'verbose_name': 'Análise Concluída K23x',
                'verbose_name_plural': 'Análises Concluídas K23x',
            },
        ),
        migrations.CreateModel(
            name='analise_concluida_k25x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_finalizada', models.DateField(blank=True, null=True, verbose_name='Data Finalizada')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('mes_sped', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês do SPED')),
                ('ano_sped', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do SPED')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
            ],
            options={
                'verbose_name': 'Análise Concluída K25x',
                'verbose_name_plural': 'Análises Concluídas K25x',
            },
        ),
        migrations.CreateModel(
            name='analise_em_andamento_k23x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('ano_sped', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do SPED')),
                ('jan', models.BooleanField(default=False, verbose_name='Janeiro')),
                ('fev', models.BooleanField(default=False, verbose_name='Fevereiro')),
                ('mar', models.BooleanField(default=False, verbose_name='Março')),
                ('abr', models.BooleanField(default=False, verbose_name='Abril')),
                ('mai', models.BooleanField(default=False, verbose_name='Maio')),
                ('jun', models.BooleanField(default=False, verbose_name='Junho')),
                ('jul', models.BooleanField(default=False, verbose_name='Julho')),
                ('ago', models.BooleanField(default=False, verbose_name='Agosto')),
                ('set', models.BooleanField(default=False, verbose_name='Setembro')),
                ('out', models.BooleanField(default=False, verbose_name='Outubro')),
                ('nov', models.BooleanField(default=False, verbose_name='Novembro')),
                ('dez', models.BooleanField(default=False, verbose_name='Dezembro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
            ],
            options={
                'verbose_name': 'Análise em Andamento K23x',
                'verbose_name_plural': 'Análises em Andamento K23x',
            },
        ),
        migrations.CreateModel(
            name='analise_em_andamento_k25x',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('ano_sped', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do SPED')),
                ('mes_sped', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês do SPED')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
            ],
            options={
                'verbose_name': 'Análise em Andamento K25x',
                'verbose_name_plural': 'Análises em Andamento K25x',
            },
        ),
        migrations.CreateModel(
            name='ItensProduzidos230',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(blank=True, max_length=5, null=True, verbose_name='Registro')),
                ('data_inicial_op', models.DateField(blank=True, null=True, verbose_name='Data Inicial da Operação')),
                ('data_final_op', models.DateField(blank=True, null=True, verbose_name='Data Final da Operação')),
                ('cod_ordem_prod', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Ordem de Produção')),
                ('codigo_item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Item')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('mes_referencia_k230', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês Referência do K230')),
                ('qtd_producao_acabada', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantidade Produção Acabada')),
                ('ano_sped', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do Sped')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
            ],
            options={
                'verbose_name': 'Item Produzido K230',
                'verbose_name_plural': 'Itens Produzidos K230',
            },
        ),
        migrations.CreateModel(
            name='InsumosUsados235',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(blank=True, max_length=5, null=True, verbose_name='Registro')),
                ('data_saida_estoque', models.DateField(blank=True, null=True, verbose_name='Data de Saída do Estoque')),
                ('codigo_item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Item')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('codigo_insumo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Insumo')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('situacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação')),
                ('verificacao_codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Verificação do Código')),
                ('ano_sped', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do SPED')),
                ('mes_referencia_k235', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês de Referência do K235')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
                ('item_produzido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metodo_rateio.itensproduzidos230')),
            ],
            options={
                'verbose_name': 'Insumo Usado K235',
                'verbose_name_plural': 'Insumos Usados K235',
            },
        ),
        migrations.CreateModel(
            name='ItensProduzidos250',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('registro', models.CharField(blank=True, max_length=5, null=True, verbose_name='Registro')),
                ('data_prod', models.DateField(blank=True, null=True, verbose_name='Data de Produção')),
                ('cod_item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Item')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('ano_sped', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano do SPED')),
                ('mes_sped', models.CharField(blank=True, max_length=18, null=True, verbose_name='Mês do SPED')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
            ],
            options={
                'verbose_name': 'Item Produzido K250',
                'verbose_name_plural': 'Itens Produzidos K250',
            },
        ),
        migrations.CreateModel(
            name='InsumosUsados255',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('registro', models.CharField(blank=True, max_length=5, null=True, verbose_name='Registro')),
                ('ano_sped', models.CharField(blank=True, null=True, verbose_name='Ano do SPED')),
                ('data_consumo_insumo', models.DateField(blank=True, null=True, verbose_name='Data de Consumo do Insumo')),
                ('cod_item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Item')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('cod_insumo_subs', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Insumo Substituição')),
                ('mes_sped', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês do SPED')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa')),
                ('k250_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metodo_rateio.itensproduzidos250')),
            ],
            options={
                'verbose_name': 'Insumo Usado K255',
                'verbose_name_plural': 'Insumos Usados K255',
            },
        ),
    ]
