# Generated by Django 6.0.4 on 2026-06-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metodo_rateio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insumosusados235",
            name="status",
        ),
        migrations.RemoveField(
            model_name="insumosusados255",
            name="status",
        ),
        migrations.RemoveField(
            model_name="itensproduzidos230",
            name="status",
        ),
        migrations.RemoveField(
            model_name="itensproduzidos250",
            name="status",
        ),
    ]
