# Generated by Django 6.0.4 on 2026-06-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metodo_rateio", "0002_remove_insumosusados235_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insumosusados235",
            name="codigo_item",
        ),
    ]
