# Generated by Django 6.0.4 on 2026-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metodo_rateio", "0003_remove_insumosusados235_codigo_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insumosusados255",
            name="cod_insumo_subs",
        ),
        migrations.AddField(
            model_name="insumosusados255",
            name="qtd_perda",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Quantidade de perda"
            ),
        ),
    ]
