# Generated by Django 6.0.4 on 2026-07-31 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metodo_rateio", "0004_remove_insumosusados255_cod_insumo_subs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="abr",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="ago",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="dez",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="fev",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="jan",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="jul",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="jun",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="mai",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="mar",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="nov",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="out",
        ),
        migrations.RemoveField(
            model_name="analise_em_andamento_k23x",
            name="set",
        ),
    ]
