# Generated by Django 6.0.4 on 2026-07-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0032_empresa_status"),
        ("metodo_rateio", "0005_remove_analise_em_andamento_k23x_abr_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="analise_em_andamento_k23x",
            new_name="analise_k23x",
        ),
        migrations.RenameModel(
            old_name="analise_em_andamento_k25x",
            new_name="analise_k25x",
        ),
        migrations.RemoveField(
            model_name="analise_concluida_k25x",
            name="empresa",
        ),
        migrations.DeleteModel(
            name="analise_concluida_k23x",
        ),
        migrations.DeleteModel(
            name="analise_concluida_k25x",
        ),
    ]
