# Generated by Django 6.0.4 on 2026-07-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "metodo_rateio",
            "0006_rename_analise_em_andamento_k23x_analise_k23x_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analise_k23x",
            name="status",
        ),
        migrations.RemoveField(
            model_name="analise_k25x",
            name="status",
        ),
        migrations.AlterField(
            model_name="analise_k23x",
            name="ano_sped",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
